/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * The name of something, as a non-empty string.
 */
export type Name = string;
/**
 * The names of multiple things, as an array of names.
 */
export type MultipleNames = Name[];
/**
 * The source for the data for this dataset.
 */
export type Data = {source: "inline" | "external"; path?: string; format?: string};

/**
 * The data, parameters and settings needed to present a chart in ParaCharts. @public
 */
export interface Manifest {
  /**
   * The data and parameters needed to present a chart in ParaCharts.
   */
  datasets: Dataset[];
}
/**
 * A set of data and parameters needed to present a chart in ParaCharts.
 */
export interface Dataset {
  /**
   * The type of the chart, such as 'line' or 'column'.
   */
  type:
    | "line"
    | "stepline"
    | "bar"
    | "column"
    | "lollipop"
    | "histogram"
    | "waterfall"
    | "scatter"
    | "heatmap"
    | "pie"
    | "donut"
    | "graph";
  /**
   * The title of the chart.
   */
  title: string;
  /**
   * The subtitle of the chart.
   */
  subtitle?: string;
  /**
   * A manually created description of the whole chart.
   */
  description?: string;
  chartTheme?: Theme;
  /**
   * Metadata describing each facet of the chart which represents some dimension of the data.
   */
  facets: {
    [k: string]: Facet;
  };
  /**
   * Metadata, and possibly inline data, describing the series of the chart.
   */
  series: SeriesManifest[];
  /**
   * How series are related to each other in multi-series bar family charts. Defaults to 'stacked'.
   */
  seriesRelations?: "stacked" | "grouped";
  data: Data;
  settings?: Settings;
}
/**
 * What quantities the line chart displays overall. Defaults to the theme of the single series ONLY in single series charts.
 */
export interface Theme {
  /**
   * The base quantity or quantities measured by the series or chart, such as 'item price' or 'inflation rate'.
   */
  baseQuantity: Name | MultipleNames;
  /**
   * What kind of base quantity this is: either a number of things (number), a quantity measured by a unit (dimensioned), a rate of change (rate), or a proportion of a whole (proportion).
   */
  baseKind: "number" | "dimensioned" | "rate" | "proportion";
  /**
   * The particular location or locations that the quantity measured by this series or chart is limited to, if any.
   */
  locale?: Name | MultipleNames;
  /**
   * The particular entity or entities the quantity measured by this series or chart belongs to, if any.
   */
  entity?: Name | MultipleNames;
  /**
   * The name of something, as a non-empty string.
   */
  items?: string;
  /**
   * The statistical aggregate or aggregates measured by this series or chart, such as 'total' or 'estimated', if any.
   */
  aggregate?: Name | MultipleNames;
}
/**
 * Metadata describing a facet of the chart which represents some dimension of the data.
 */
export interface Facet {
  /**
   * The name of something, as a non-empty string.
   */
  label: string;
  /**
   * An extended text description for the quantity measured by this facet.
   */
  description?: string;
  /**
   * Whether the variable this facet measures depends on the variable measured by another facet or facets.
   */
  variableType: "dependent" | "independent";
  /**
   * The NOIR data scale of the quantity this facet measures.
   */
  measure: "nominal" | "ordinal" | "interval" | "ratio";
  /**
   * The primitive type of the data measured by this facet.
   */
  datatype: "number" | "date" | "string";
  displayType: DisplayType;
  /**
   * The name of something, as a non-empty string.
   */
  units?: string;
  /**
   * The number each datum of this facet must be multiplied by to get the true value. Defaults to 1.
   */
  multiplier?: number;
  /**
   * The name of something, as a non-empty string.
   */
  denominator?: string;
}
/**
 * How this facet should be displayed on the chart
 */
export interface DisplayType {
  /**
   * What type of chart element represents the facet.
   */
  type: "axis" | "marking" | "area" | "angle";
  /**
   * What type of chart element represents the facet.
   */
  orientation?: "horizontal" | "vertical";
  /**
   * The lowest value displayed on this axis of the chart. Defaults to zero for the dependent axis and the minimum independent value of any series for the independent axis.
   */
  minDisplayed?: number;
  /**
   * The highest value label displayed on this axis of the chart. Defaults to the maximum value of any series relative to this axis.
   */
  maxDisplayed?: number;
}
/**
 * Metadata, and possibly inline data, describing a series on the chart.
 */
export interface SeriesManifest {
  /**
   * A unique identifier for the series, which may have spaces, punctuation, or other non-alphanumeric characters that aren't allowed in DOM ids, but which still may not be suitable for the text label.
   */
  key: string;
  /**
   * The text label for the series, which may be abbreviated or expanded from the series key. Defaults to key.
   */
  label?: string;
  theme?: Theme1;
  /**
   * The datapoints of this series represented inline.
   */
  records?: DatapointManifest[];
}
/**
 * What quantity the series measures.
 */
export interface Theme1 {
  /**
   * The base quantity or quantities measured by the series or chart, such as 'item price' or 'inflation rate'.
   */
  baseQuantity: Name | MultipleNames;
  /**
   * What kind of base quantity this is: either a number of things (number), a quantity measured by a unit (dimensioned), a rate of change (rate), or a proportion of a whole (proportion).
   */
  baseKind: "number" | "dimensioned" | "rate" | "proportion";
  /**
   * The particular location or locations that the quantity measured by this series or chart is limited to, if any.
   */
  locale?: Name | MultipleNames;
  /**
   * The particular entity or entities the quantity measured by this series or chart belongs to, if any.
   */
  entity?: Name | MultipleNames;
  /**
   * The name of something, as a non-empty string.
   */
  items?: string;
  /**
   * The statistical aggregate or aggregates measured by this series or chart, such as 'total' or 'estimated', if any.
   */
  aggregate?: Name | MultipleNames;
}
/**
 * A datapoint on the graph.
 */
export interface DatapointManifest {
  /**
   * The value of the point relative to the facet labelled by this property key.
   */
  [k: string]: string;
}
/**
 * The settings needed to present a chart in ParaCharts.
 */
export interface Settings {
  /**
   * Sonification Settings
   */
  sonification?: {
    /**
     * Whether sonification is enabled for this chart. Defaults to true.
     */
    isSoniEnabled?: boolean;
    [k: string]: unknown;
  };
  /**
   * The ratio of the height to the width of the chart on the screen (i.e. x-axis size / y-axis size). Defaults to 1 (i.e. a square chart).
   */
  aspectRatio?: number;
  /**
   * Settings for each Axis
   */
  axis?: {
    x?: AxisSettings;
    y?: AxisSettings1;
    [k: string]: unknown;
  };
  [k: string]: unknown;
}
/**
 * X Axis Settings
 */
export interface AxisSettings {
  /**
   * The minimum value of the axis.
   */
  minValue?: number | "unset";
  /**
   * The maximum value of the axis.
   */
  maxValue?: number | "unset";
  [k: string]: unknown;
}
/**
 * Y Axis Settings
 */
export interface AxisSettings1 {
  /**
   * The minimum value of the axis.
   */
  minValue?: number | "unset";
  /**
   * The maximum value of the axis.
   */
  maxValue?: number | "unset";
  [k: string]: unknown;
}
