/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * The source for the data for this dataset.
 */
export type Data = {source: "inline" | "external"; path?: string; format?: string};

/**
 * The data, parameters and settings needed to present a chart in ParaCharts. @public
 */
export interface Manifest {
  /**
   * The data and parameters needed to present a chart in ParaCharts.
   */
  datasets: Dataset[];
}
/**
 * A set of data and parameters needed to present a chart in ParaCharts.
 */
export interface Dataset {
  /**
   * The type of the chart, such as 'line' or 'column'.
   */
  type: "line" | "column" | "bar" | "scatter" | "lollipop" | "stepline" | "pie" | "donut";
  /**
   * The title of the chart.
   */
  title: string;
  chartTheme?: Theme;
  /**
   * Metadata describing each facet of the chart which represents some dimension of the data.
   */
  facets: {
    [k: string]: Facet;
  };
  /**
   * Metadata, and possibly inline data, describing the series of the chart.
   */
  series: SeriesManifest[];
  data: Data;
  settings?: Settings;
}
/**
 * What quantities the line chart displays overall. Defaults to the theme of the single series ONLY in single series charts.
 */
export interface Theme {
  /**
   * The base quantity measured by the series or chart, such as 'item price' or 'inflation rate'.
   */
  baseQuantity: string;
  /**
   * What kind of base quantity this is: either a number of things (number), a quantity measured by a unit (dimensioned), a rate of change (rate), or a proportion of a whole (proportion).
   */
  baseKind: "number" | "dimensioned" | "rate" | "proportion";
  /**
   * The particular location that the quantity measured by this series or chart is limited to, if any.
   */
  locale?: string;
  /**
   * The singular, definite entity the quantity measured by this series or chart belongs to, if any.
   */
  entity?: string;
  /**
   * The multiple, indefinite items the quantity measured by this series or chart belongs to, if any.
   */
  items?: string;
  /**
   * The statistical aggregate measured by this series or chart, such as 'total' or 'estimated', if any.
   */
  aggregate?: string;
}
/**
 * Metadata describing a facet of the chart which represents some dimension of the data.
 */
export interface Facet {
  /**
   * A text label for the quantity measured by this facet.
   */
  label: string;
  /**
   * An extended text description for the quantity measured by this facet.
   */
  description?: string;
  /**
   * Whether the variable this facet measures depends on the variable measured by another facet or facets.
   */
  variableType: "dependent" | "independent";
  /**
   * The NOIR data scale of the quantity this facet measures.
   */
  measure: "nominal" | "ordinal" | "interval" | "ratio";
  /**
   * The primitive type of the data measured by this facet.
   */
  datatype: "number" | "date" | "string";
  displayType: DisplayType;
  /**
   * The units for the data of this facet, in singular form, if any. This value should be absent if the facet measures a dimensionless quantity. If the units for this facet of the chart are fractional, then this is only the numerator of that fraction.
   */
  units?: string;
  /**
   * The number each datum of this facet must be multiplied by to get the true value. Defaults to 1.
   */
  multiplier?: number;
  /**
   * If the units for this facet of the chart are fractional, then this is the denominator of that fraction. For example: '(per) capita', '(per) million inhabitants'. If this property is present, then every series on the chart must measure a fractional quantity, of which this will also be the denominator.
   */
  denominator?: string;
}
/**
 * How this facet should be displayed on the chart
 */
export interface DisplayType {
  /**
   * What type of chart element represents the facet.
   */
  type: "axis" | "marking" | "area" | "angle";
  /**
   * What type of chart element represents the facet.
   */
  orientation?: "horizontal" | "vertical";
  /**
   * The lowest value displayed on this axis of the chart. Defaults to zero for the dependent axis and the minimum independent value of any series for the independent axis.
   */
  minDisplayed?: number;
  /**
   * The highest value label displayed on this axis of the chart. Defaults to the maximum value of any series relative to this axis.
   */
  maxDisplayed?: number;
}
/**
 * Metadata, and possibly inline data, describing a series on the chart.
 */
export interface SeriesManifest {
  /**
   * A unique identifier for the series, which may have spaces, punctuation, or other non-alphanumeric characters that aren't allowed in DOM ids, but which still may not be suitable for the text label.
   */
  key: string;
  /**
   * The text label for the series, which may be abbreviated or expanded from the series key. Defaults to key.
   */
  label?: string;
  theme: Theme1;
  /**
   * The datapoints of this series represented inline.
   */
  records?: Datapoint[];
}
/**
 * What quantity the series measures.
 */
export interface Theme1 {
  /**
   * The base quantity measured by the series or chart, such as 'item price' or 'inflation rate'.
   */
  baseQuantity: string;
  /**
   * What kind of base quantity this is: either a number of things (number), a quantity measured by a unit (dimensioned), a rate of change (rate), or a proportion of a whole (proportion).
   */
  baseKind: "number" | "dimensioned" | "rate" | "proportion";
  /**
   * The particular location that the quantity measured by this series or chart is limited to, if any.
   */
  locale?: string;
  /**
   * The singular, definite entity the quantity measured by this series or chart belongs to, if any.
   */
  entity?: string;
  /**
   * The multiple, indefinite items the quantity measured by this series or chart belongs to, if any.
   */
  items?: string;
  /**
   * The statistical aggregate measured by this series or chart, such as 'total' or 'estimated', if any.
   */
  aggregate?: string;
}
/**
 * A datapoint on the graph.
 */
export interface Datapoint {
  /**
   * The value of the point relative to the facet labelled by this property key.
   */
  [k: string]: string;
}
/**
 * The settings needed to present a chart in ParaCharts.
 */
export interface Settings {
  /**
   * Whether sonification is enabled for this chart. Defaults to true.
   */
  "sonification.isEnabled"?: boolean;
  /**
   * The ratio of the height to the width of the chart on the screen (i.e. x-axis size / y-axis size). Defaults to 1 (i.e. a square chart).
   */
  aspectRatio?: number;
}
