/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * The name of something, as a non-empty string.
 */
export type Name = string;
/**
 * The names of multiple things, as an array of names.
 */
export type MultipleNames = Name[];
/**
 * A datapoint on the graph.
 */
export type DatapointManifest = {properties?: {type: "total"; [k: string]: string}} & {[k: string]: string};
/**
 * The source for the data for this dataset.
 */
export type Data = {source: "inline" | "external"; path?: string; format?: string};

/**
 * Metadata, and optionally inline data, needed to present a ParaCharts element, as a root form JIM document. @public
 */
export interface JIMManifest {
  /**
   * Metadata, and optionally inline data, needed to present a chart in ParaCharts.
   */
  datasets: Dataset[];
}
/**
 * A set of data and parameters needed to present a chart in ParaCharts.
 */
export interface Dataset {
  /**
   * In what form the data is presented in the ParaChart element.
   */
  representation: {
    /**
     * The type of the visualization, which is always 'chart'.
     */
    type: "chart";
    /**
     * The type of the chart, such as 'line' or 'column'.
     */
    subtype:
      | "line"
      | "stepline"
      | "bar"
      | "column"
      | "lollipop"
      | "histogram"
      | "waterfall"
      | "scatter"
      | "heatmap"
      | "pie"
      | "donut"
      | "graph"
      | "venn";
  };
  /**
   * The title of the chart.
   */
  title: string;
  /**
   * The subtitle of the chart.
   */
  subtitle?: string;
  /**
   * A manually created description of the whole chart.
   */
  description?: string;
  chartTheme?: Theme;
  /**
   * Metadata describing each facet of the chart which represents some dimension of the data.
   */
  facets: {
    [k: string]: Facet;
  };
  /**
   * Metadata, and possibly inline data, describing the series of the chart.
   */
  series: SeriesManifest[];
  /**
   * How series are related to each other in multi-series bar family charts. Defaults to 'stacked'.
   */
  seriesRelations?: "stacked" | "grouped";
  data: Data;
}
/**
 * What quantities the line chart displays overall. Defaults to the theme of the single series ONLY in single series charts.
 */
export interface Theme {
  /**
   * The base quantity or quantities measured by the series or chart, such as 'item price' or 'inflation rate'.
   */
  baseQuantity: Name | MultipleNames;
  /**
   * What kind of base quantity this is: either a number of things (number), a quantity measured by a unit (dimensioned), a rate of change (rate), or a proportion of a whole (proportion).
   */
  baseKind: "number" | "dimensioned" | "rate" | "proportion";
  /**
   * The particular location or locations that the quantity measured by this series or chart is limited to, if any.
   */
  locale?: Name | MultipleNames;
  /**
   * The particular entity or entities the quantity measured by this series or chart belongs to, if any.
   */
  entity?: Name | MultipleNames;
  /**
   * A general term or terms for the multiple, indefinite items the quantity measured by this series or chart belongs to, if any.
   */
  items?: Name | MultipleNames;
  /**
   * The statistical aggregate or aggregates measured by this series or chart, such as 'total' or 'estimated', if any.
   */
  aggregate?: Name | MultipleNames;
}
/**
 * Metadata describing a facet of the chart which represents some dimension of the data.
 */
export interface Facet {
  /**
   * The name of something, as a non-empty string.
   */
  label: string;
  /**
   * An extended text description for the quantity measured by this facet.
   */
  description?: string;
  /**
   * Whether the variable this facet measures depends on the variable measured by another facet or facets.
   */
  variableType: "dependent" | "independent";
  /**
   * The NOIR data scale of the quantity this facet measures.
   */
  measure: "nominal" | "ordinal" | "interval" | "ratio";
  /**
   * The primitive type of the data measured by this facet.
   */
  datatype: "number" | "date" | "string";
  displayType: DisplayType;
  /**
   * The name of something, as a non-empty string.
   */
  units?: string;
  /**
   * The number each datum of this facet must be multiplied by to get the true value. Defaults to 1.
   */
  multiplier?: number;
  /**
   * The name of something, as a non-empty string.
   */
  denominator?: string;
  /**
   * A text label for specific values of the facet, to be used for axis labels and similar purposes. Each property key represents a raw value of the facet and each property value represents the label that facet value should have.
   */
  valueLabels?: {
    [k: string]: string;
  };
}
/**
 * How this facet should be displayed on the chart
 */
export interface DisplayType {
  /**
   * What type of chart element represents the facet.
   */
  type: "axis" | "marking" | "area" | "angle" | "text";
  /**
   * What type of chart element represents the facet.
   */
  orientation?: "horizontal" | "vertical";
  /**
   * The lowest value displayed on this axis of the chart. Defaults to zero for the dependent axis and the minimum independent value of any series for the independent axis.
   */
  minDisplayed?: number;
  /**
   * The highest value label displayed on this axis of the chart. Defaults to the maximum value of any series relative to this axis.
   */
  maxDisplayed?: number;
}
/**
 * Metadata, and possibly inline data, describing a series on the chart.
 */
export interface SeriesManifest {
  /**
   * A unique identifier for the series, which may have spaces, punctuation, or other non-alphanumeric characters that aren't allowed in DOM ids, but which still may not be suitable for the text label.
   */
  key: string;
  /**
   * The text label for the series, which may be abbreviated or expanded from the series key. Defaults to key.
   */
  label?: string;
  theme?: Theme1;
  /**
   * The datapoints of this series represented inline.
   */
  records?: DatapointManifest[];
}
/**
 * What quantity the series measures.
 */
export interface Theme1 {
  /**
   * The base quantity or quantities measured by the series or chart, such as 'item price' or 'inflation rate'.
   */
  baseQuantity: Name | MultipleNames;
  /**
   * What kind of base quantity this is: either a number of things (number), a quantity measured by a unit (dimensioned), a rate of change (rate), or a proportion of a whole (proportion).
   */
  baseKind: "number" | "dimensioned" | "rate" | "proportion";
  /**
   * The particular location or locations that the quantity measured by this series or chart is limited to, if any.
   */
  locale?: Name | MultipleNames;
  /**
   * The particular entity or entities the quantity measured by this series or chart belongs to, if any.
   */
  entity?: Name | MultipleNames;
  /**
   * A general term or terms for the multiple, indefinite items the quantity measured by this series or chart belongs to, if any.
   */
  items?: Name | MultipleNames;
  /**
   * The statistical aggregate or aggregates measured by this series or chart, such as 'total' or 'estimated', if any.
   */
  aggregate?: Name | MultipleNames;
}
